### PR TITLE
#12: bumped css-selector requirements

### PR DESCRIPTION
**Pull request by JanDC**
This should provide support for symfony 4.*

### CODE REVIEW

**Comment by poveu** [comment]
Do you plan to merge this fix with master branch?

**Comment by JanDC** [comment]
> Do you plan to merge this fix with master branch?

I plan to, but I'm wary for regressions.
Chances are I'm testing it this weekend...

**Comment by nevenduranec** [comment]
Hi, is there any chance of this getting merged?

**Comment by JanDC** [comment]
Hi @poveu / @nevenduranec ,

I've merged this PR and released an alpha release with the updated requirements.
I hope I can review the alpha in a symfony project myself, but I'm always short on time.

In the meantime I'd appreciate any feedback on your experiences...

**Pull request merged**
